In [41]:
import numpy as np

x = np.array([[1, 5, 100, 202],
            [2, 4,100, 21]])
x1 = np.array([3, 3, 2 , 4])



def softmax(x):
    if x.ndim == 2:
        x = x.T
        x = x - np.max(x, axis = 0)
        y = np.exp(x) / np.sum(np.exp(x), axis = 0)
        return y.T
    
    x = x - np.max(x)
    return np.exp(x) / np.sum(np.exp(x))

print(softmax(x))
print(softmax(x1))

[[5.09107081e-88 2.77963048e-86 5.03457536e-45 1.00000000e+00]
 [2.74878501e-43 2.03109266e-42 1.00000000e+00 4.90609473e-35]]
[0.19661193 0.19661193 0.07232949 0.53444665]


In [42]:
import numpy as np

class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None
    def forward(self, x, y):
        self.x = x
        self.y = y
        return x * y
    def backward(self, dout):
        dx = dout * self.y
        dy = dout * self.x
        return dx, dy

class Affine:
    def __init__(self, W, b):
        self.W = W
        self.b = b
        self.x = None
        self.dw = None
        self.db = None
    def forward(self, x):
        self.x = x
        out = np.dot(x, self.W) + self.b
        return out
    
    def backward(self, dout):
        dx = np.dot(dout, self.W.T)
        self.dw = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis = 0)
        
        return dx

In [62]:
import numpy as np
y1 = np.array([0.1, 0.05, 0, 0.6, 0, 0.1, 0, 0.4, 0.05, 0])
t1 = np.array([0,0,0,1,0,0,0,0,0,0])

y2 = np.array([[0.1, 0.05, 0, 0.6, 0, 0.1, 0, 0.4, 0.05, 0],
              [0.1, 0.05, 0, 0.06,0,0.1,0,0.4,0.5,0]])
t2 = np.array([[0,0,0,1,0,0,0,0,0,0],
              [0,0,0,0,0,0,0,0,1,0]])

t2 = t2.argmax(axis=1)
print(t2)
batch_size = y2.shape[0]
print(np.arange(batch_size))
y2[np.arange(batch_size), t2] + 1e-7


[3 8]
[0 1]


array([0.6000001, 0.5000001])

In [64]:
a = np.array([[1,2],
          [3,4]])
b = np.zeros_like(a)
for idx, x in enumerate(a):
    print(idx, x)
    b[idx] = 

0 [1 2]
1 [3 4]
